name: Prueba Python

on:

  workflow_dispatch:

jobs:

  python:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Ejecutar script
        run: |
          python main.py
