name: VTEX Catalogo

on:

  workflow_dispatch:

  schedule:
    - cron: '0 8 * * *'

jobs:

  catalogo:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar catalogo
        run: |
          python main.py
          
      - name: Ver tamaño CSV
        run: |
          ls -lh catalogo_CAM.csv
          
      - name: Guardar CSV
        uses: actions/upload-artifact@v4
        with:
          name: catalogo_CAM
          path: catalogo_CAM.csv
